In [2]:
import torch

In [3]:
import numpy as np

### torch 基本处理单元

In [5]:
# 返回的数组大小5x4的矩阵
torch.Tensor(5, 4)

tensor([[-4.0790e-24,  4.5737e-41, -4.0790e-24,  4.5737e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.8788e+31,  1.7220e+22],
        [ 1.1970e+22,  1.0563e-05,  1.2857e-11,  1.6821e-04],
        [ 2.1629e+23,  1.3666e+22,  5.3974e-05,  3.3242e+21]])

In [6]:
# 返回的数组大小是5x4的矩阵，初始化是0~1的均匀分布
torch.rand(5, 4)

tensor([[0.0136, 0.1146, 0.7065, 0.2566],
        [0.4399, 0.5841, 0.3432, 0.0589],
        [0.3141, 0.2398, 0.2793, 0.3053],
        [0.7336, 0.0690, 0.5683, 0.1211],
        [0.3972, 0.5709, 0.5106, 0.8231]])

In [7]:
# 得到矩阵大小
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [8]:
# numpy 类似的返回5x4大小的矩阵
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# numpy 和 torch.Tensor 之间的转换
a = torch.rand(5, 4)
b = a.numpy()
print(b)

[[0.23093104 0.90491307 0.50040734 0.46130127]
 [0.6242984  0.21154219 0.11396891 0.00677162]
 [0.86012137 0.9592093  0.24215615 0.6900894 ]
 [0.30996364 0.812516   0.05599403 0.22562134]
 [0.44982022 0.45009744 0.01207632 0.4513023 ]]


In [10]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [3, 6]])


运算和numpy类似

In [12]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [13]:
print(c * x)

tensor([[2.9527, 0.6805, 1.9412, 2.6876],
        [2.5958, 2.8978, 0.6307, 2.0800],
        [0.1231, 2.5987, 0.8466, 0.8304],
        [1.2684, 0.5182, 0.7438, 2.6416],
        [2.1507, 1.9319, 0.3298, 2.7190]])


In [14]:
print(x + y)

tensor([[1.8817, 0.2605, 1.6271, 1.2533],
        [1.2475, 1.7266, 0.5682, 1.3952],
        [0.6200, 1.6122, 0.4683, 1.2351],
        [0.8005, 0.3558, 0.5066, 0.9087],
        [1.6053, 0.7238, 0.1725, 1.2386]])


In [15]:
print(x.add(y))

tensor([[1.8817, 0.2605, 1.6271, 1.2533],
        [1.2475, 1.7266, 0.5682, 1.3952],
        [0.6200, 1.6122, 0.4683, 1.2351],
        [0.8005, 0.3558, 0.5066, 0.9087],
        [1.6053, 0.7238, 0.1725, 1.2386]])


In [16]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)

tensor([[1.8817, 0.2605, 1.6271, 1.2533],
        [1.2475, 1.7266, 0.5682, 1.3952],
        [0.6200, 1.6122, 0.4683, 1.2351],
        [0.8005, 0.3558, 0.5066, 0.9087],
        [1.6053, 0.7238, 0.1725, 1.2386]])

In [17]:
print(x)

tensor([[1.8817, 0.2605, 1.6271, 1.2533],
        [1.2475, 1.7266, 0.5682, 1.3952],
        [0.6200, 1.6122, 0.4683, 1.2351],
        [0.8005, 0.3558, 0.5066, 0.9087],
        [1.6053, 0.7238, 0.1725, 1.2386]])


将 torch.Tensor 放到 GPU 上

In [18]:
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

True

In [19]:
a = torch.rand(5, 4)
a = a.cuda()
print(a)

tensor([[0.7165, 0.4812, 0.2382, 0.9995],
        [0.1362, 0.6725, 0.7586, 0.0124],
        [0.1504, 0.3804, 0.1812, 0.4680],
        [0.4265, 0.6717, 0.9109, 0.6045],
        [0.2095, 0.6686, 0.9919, 0.7787]], device='cuda:0')


### torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是torch.autograd.Variable

本质上Variable和Tensor没有什么区别，不过Variable会放在一个计算图里面，可以进行前向传播和反向传播以及求导  

![1.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

里面的creator表示通过什么操作得到的这个Variable，grad表示反向传播的梯度

In [20]:
from torch.autograd import Variable

In [21]:
# requires_grad 表示是否对其求梯度，默认是False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [22]:
# 对 x 和 y 分别求导
z.backward()

In [23]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


### 神经网络部分

所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作

In [24]:
from torch import nn
import torch.nn.functional as F

In [25]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out