In [20]:
import torch
import numpy as np

In [14]:
torch.Tensor(5,4)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.3593e-43, 0.0000e+00]])

In [18]:
a = torch.rand(5, 4)
b = a.numpy()
print(b)

[[0.44949377 0.10505652 0.32929564 0.4553082 ]
 [0.72672904 0.7774341  0.42356288 0.94176984]
 [0.67239726 0.1617117  0.8273005  0.86754256]
 [0.08535928 0.57708216 0.07351208 0.5663145 ]
 [0.2532521  0.27591914 0.07590371 0.07242906]]


In [21]:
a = np.array([[3,4], [3, 6]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [3, 6]])


In [ ]:
## Variable

In [36]:
from torch.autograd import Variable 

In [37]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2*x+y+4

In [38]:
z.backward()

In [39]:
print("{}".format(x.grad.data))
print("{}".format(y.grad.data))

tensor([2.])
tensor([1.])


In [32]:
## Neural Network 
## basic template

In [40]:
from torch import nn
import torch.nn.functional as F

In [35]:
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        self.conv1 = nn.Conv2d(3, 10, 3)
    
    def forward(self, x):
        out = self.conv1(x)
        return out